title: An√°lisis de la actividad de 4 proyectos Open Source en plena pandemia del COVID-19
description: Analisis Actividad de proyectos Open source
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile